spring:
  datasource:
    url: jdbc:sqlite:./data/import-framework.db
    driver-class-name: org.sqlite.JDBC

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB